version: '3.1'

services:
  zookeeper:
    image: 'bitnami/zookeeper:3'
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:2'
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_HOST_NAME=kafka
    depends_on:
      - zookeeper

  db:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=test
    volumes:
      - 'postgresql:/var/lib/postgresql'
      - 'postgresql_data:/var/lib/postgresql/data'

  producer:
    build: src/producer/
    ports:
      - '5000:5000'
    command: producer -i data/events.json -d
    depends_on:
      - kafka

  consumer:
    build: src/consumer/
    ports:
      - '5001:5001'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=test
    command: consumer -d
    depends_on:
      - kafka
      - db

  spark-master:
    image: gettyimages/spark
    ports:
      - '4040:4040'
      - '6066:6066'
      - '7077:7077'
      - '8080:8080'
    expose:
      - '7001'
      - '7002'
      - '7003'
      - '7004'
      - '7005'
      - '7077'
      - '6066'
    environment:
      - MASTER=spark://spark-master:7077
      - SPARK_CONF_DIR=/conf
      - SPARK_PUBLIC_DNS=localhost
    command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
    hostname: spark-master
    volumes:
      - './conf/master:/conf'
      - './data:/tmp/data'

  spark-worker:
    image: gettyimages/spark
    ports:
      - '8081:8081'
    expose:
      - '7012'
      - '7013'
      - '7014'
      - '7015'
      - '8881'
    links:
      - spark-master
    environment:
      - SPARK_CONF_DIR=/conf
      - SPARK_PUBLIC_DNS=localhost
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=1g
      - SPARK_WORKER_PORT=8881
      - SPARK_WORKER_WEBUI_PORT=8081
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    hostname: spark-worker
    volumes:
      - './conf/worker:/conf'
      - './data:/tmp/data'

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  postgresql:
  postgresql_data:
